# -*- coding: utf-8 -*-
{
    'name': "Real Estate",
    'version': '17.0',
    'summary': """Real Estate, property, rental, ownership, installments, management, projects, marketing, villa, 
    buildings, lands """,
    'description': """Introducing our cutting-edge Real Estate Odoo App, a seamlessly integrated solution designed to 
    revolutionize the real estate management experience. With an intuitive and user-friendly interface, this system 
    caters to both English and Arabic speakers, ensuring accessibility for a diverse range of users.""",
    'author': 'Neoteric Hub',
    'company': 'Neoteric Hub',
    'live_test_url': '',
    'price': 699,
    'currency': 'USD',
    'website': "https://www.neoterichub.com",
    'depends': ['base', 'mail', 'product', 'purchase', 'contacts', 'account', 'product', 'stock', 'board','analytic'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/reservation_sequence.xml',
        'data/mail_template.xml',
        'data/contract_sequence.xml',
        'data/real_estate_demo_data.xml',
        'views/regions_views.xml',
        'views/installment_template_view.xml',
        'views/main_property_views.xml',
        'views/sub_property_views.xml',
        'views/main_property_type_views.xml',
        'views/property_status.xml',
        'views/property_description.xml',
        'views/partner_view.xml',
        'views/furniture_views.xml',
        'views/rental_contract_views.xml',
        'views/rental_settlement.xml',
        'views/ownership_contract.xml',
        'views/ownership_settlement.xml',
        'views/reservation_view.xml',
        'views/configuration_views.xml',
        'views/dashboard.xml',
        'views/menu_views.xml',
        'report/ownership_template.xml',
        'report/rental_contracts_template.xml',
        'report/reservation_template.xml',
    ],
    'images': ['static/description/banner.gif'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
