# -*- coding: utf-8 -*-
{
    'name': 'SMAC Construction Management',
    'summary': 'Manage construction projects, contracts, invoices, deductions, and approval workflows',
    'description': 'Construction project and subcontractor contract management for Odoo 18.',
    'author': 'SMAC',
    'website': 'http://www.smac.com',
    'category': 'Services/Project',
    'version': '18.0.1.0.0',
    'license': 'LGPL-3',
    'application': True,
    'installable': True,
    'depends': [
        'base',
        'base_setup',
        'mail',
        'portal',
        'account',
        'uom',
        'project',
        'analytic',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/construction_project.xml',
        'views/business_unit.xml',
        'views/contract_project.xml',
        'views/contract_invoice.xml',
        'views/deductions.xml',
        'views/wbs.xml',
        'views/work_package.xml',
        'views/items.xml',
        'views/disciplines.xml',
        'views/res_partner.xml',
        'views/change_request.xml',
        'views/workflow.xml',
        'views/stage.xml',
        'views/res_config_settings.xml',
        'views/res_users.xml',
        'views/equipments.xml',
        'views/man_power_types.xml',
        'views/analytic_plan.xml',
        'views/templates.xml',
    ],
}
